{
 "title": "_Kafka Finops Cost Center Detailed View",
 "tags": [ "kafka-finops" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Provider",
    "label": "Provider",
    "query": {
     "query": "label_values(finops_current_provider, provider)"
    }
   },
   {
    "name": "BusinessModel",
    "label": "Business Model",
    "query": {
     "query": "label_values(finops_current_provider, business_model)"
    }
   },
   {
    "name": "AvailabilityZones",
    "label": "Availability Zones",
    "query": {
     "query": "label_values(finops_current_provider, availability_zones)"
    }
   },
   { "name": "BusinessUnits", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align: center; font-size: 84px\">Cost Center Detailed View </p>"
   }
  },
  {
   "title": "Total unit cost",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(finops_cost_per_topic_total{business_model=\"$BusinessModel\", availability_zones=\"$AvailabilityZones\", provider=\"$Provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Detailed Costs View",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "(finops_cost_per_topic_licencing{provider=\"$Provider\", availability_zones=\"$AvailabilityZones\", business_model=\"$BusinessModel\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "(finops_cost_per_topic_operational{provider=\"$Provider\", availability_zones=\"$AvailabilityZones\", business_model=\"$BusinessModel\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "(finops_cost_per_partition{provider=\"$Provider\", availability_zones=\"$AvailabilityZones\", business_model=\"$BusinessModel\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "(finops_cost_per_topic_per_byte{provider=\"$Provider\", availability_zones=\"$AvailabilityZones\", business_model=\"$BusinessModel\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "finops_egress_network_cost_per_month_estimate{provider=\"$Provider\", availability_zones=\"$AvailabilityZones\", business_model=\"$BusinessModel\"} + \nfinops_ingress_network_cost_per_month_estimate{provider=\"$Provider\", availability_zones=\"$AvailabilityZones\", business_model=\"$BusinessModel\"}",
     "legendFormat": "Network"
    },
    {
     "expr": "finops_cost_per_topic_total{provider=\"$Provider\", availability_zones=\"$AvailabilityZones\", business_model=\"$BusinessModel\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "_Kafka Finops Global Cost Center View",
 "description": "View entire kafka cluster expenses and business units contributing to it",
 "tags": [ "kafka-finops" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "provider",
    "label": "Provider",
    "query": {
     "query": "label_values(finops_current_provider, provider)"
    }
   },
   {
    "name": "businessModel",
    "label": "Business Model",
    "query": {
     "query": "label_values(finops_current_provider, business_model)"
    }
   },
   {
    "name": "az",
    "label": "Availability Zone",
    "query": {
     "query": "label_values(finops_current_provider, availability_zones)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align: center; font-size: 84px\">Global Cost Center View </p>"
   }
  },
  {
   "title": "Business Unit total costs",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "USD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(business_unit) (finops_cost_per_topic_total{business_model=\"$businessModel\", provider=\"$provider\", availability_zones=\"$az\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monthly costs breakup",
   "type": "table",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "USD" } },
   "targets": [
    {
     "expr": "finops_cost_per_topic_licencing{business_model=\"$businessModel\", provider=\"$provider\", availability_zones=\"$az\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "finops_cost_per_topic_operational{business_model=\"$businessModel\", provider=\"$provider\", availability_zones=\"$az\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "finops_cost_per_partition{business_model=\"$businessModel\", provider=\"$provider\", availability_zones=\"$az\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "finops_egress_network_cost_per_month_estimate{business_model=\"$businessModel\", provider=\"$provider\", availability_zones=\"$az\"} + finops_ingress_network_cost_per_month_estimate{business_model=\"$businessModel\", provider=\"$provider\", availability_zones=\"$az\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "finops_cost_per_topic_per_byte{business_model=\"$businessModel\", provider=\"$provider\", availability_zones=\"$az\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unassigned Topics",
   "type": "table",
   "description": "Topics that are not associated with any known business units",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "finops_cost_per_topic_total{business_model=\"$businessModel\", provider=\"$provider\", business_unit=\"__NA__\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "_Kafka Finops Global Costs Comparison",
 "tags": [ "kafka-finops" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CurrentProvider",
    "query": {
     "query": "label_values(finops_current_provider, provider)"
    }
   },
   {
    "name": "CurrentBusinessModel",
    "query": {
     "query": "label_values(finops_current_provider, business_model)"
    }
   },
   {
    "name": "availableProviders",
    "query": {
     "query": "label_values(finops_cost_per_topic_total,provider)"
    }
   },
   {
    "name": "availableBusinessModels",
    "query": {
     "query": "label_values(finops_cost_per_topic_total,business_model)"
    }
   },
   {
    "name": "currentAZ",
    "query": {
     "query": "label_values(finops_current_provider, availability_zones)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Configuration (Business Model = $CurrentBusinessModel, Provider = $CurrentProvider , Availability Zone = $currentAZ )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total cost",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "USD" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "sum(finops_cost_per_topic_total{business_model=\"$CurrentBusinessModel\", provider=\"$CurrentProvider\", availability_zones=\"$currentAZ\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost breakup",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "USD" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "sum(finops_cost_per_topic_licencing{business_model=\"$CurrentBusinessModel\", provider=\"$CurrentProvider\", availability_zones=\"$currentAZ\"})",
     "legendFormat": "Licencing Cost"
    },
    {
     "expr": "sum(finops_cost_per_topic_operational{business_model=\"$CurrentBusinessModel\", provider=\"$CurrentProvider\", availability_zones=\"$currentAZ\"})",
     "legendFormat": "Operational Cost"
    },
    {
     "expr": "sum(finops_cost_per_topic_per_byte{business_model=\"$CurrentBusinessModel\", provider=\"$CurrentProvider\", availability_zones=\"$currentAZ\"})",
     "legendFormat": "Storage Cost"
    },
    {
     "expr": "sum(finops_cost_per_partition{business_model=\"$CurrentBusinessModel\", provider=\"$CurrentProvider\", availability_zones=\"$currentAZ\"})",
     "legendFormat": "Partitions Cost"
    },
    {
     "expr": "sum(finops_egress_network_cost_per_month_estimate{business_model=\"$CurrentBusinessModel\", provider=\"$CurrentProvider\", availability_zones=\"$currentAZ\"}) + sum(finops_ingress_network_cost_per_month_estimate{business_model=\"$CurrentBusinessModel\", provider=\"$CurrentProvider\", availability_zones=\"$currentAZ\"})",
     "legendFormat": "Networking Cost"
    }
   ]
  },
  { "title": "Alternative Cost Models", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Business Model Options",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "finops_cost_per_topic_licencing{provider=\"$CurrentProvider\", availability_zones=\"$currentAZ\"}",
     "legendFormat": "Licencing Cost"
    },
    {
     "expr": "finops_cost_per_topic_operational{availability_zones=\"$currentAZ\", provider=\"$CurrentProvider\"}",
     "legendFormat": "Operational Cost"
    },
    {
     "expr": "finops_cost_per_topic_per_byte{provider=\"$CurrentProvider\", availability_zones=\"$currentAZ\"}",
     "legendFormat": "Storage Cost"
    },
    {
     "expr": "finops_cost_per_partition{provider=\"$CurrentProvider\", availability_zones=\"$currentAZ\"}",
     "legendFormat": "Partition Cost"
    },
    {
     "expr": "finops_egress_network_cost_per_month_estimate{provider=\"$CurrentProvider\", availability_zones=\"$currentAZ\"} +\nfinops_ingress_network_cost_per_month_estimate{provider=\"$CurrentProvider\", availability_zones=\"$currentAZ\"}",
     "legendFormat": "Networking Cost"
    }
   ]
  },
  {
   "title": "Availability Zones Options",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "finops_cost_per_topic_licencing{business_model=\"$CurrentBusinessModel\", provider=\"$CurrentProvider\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "finops_cost_per_topic_operational{business_model=\"$CurrentBusinessModel\",provider=\"$CurrentProvider\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "finops_cost_per_topic_per_byte{business_model=\"$CurrentBusinessModel\",provider=\"$CurrentProvider\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "finops_cost_per_partition{business_model=\"$CurrentBusinessModel\",provider=\"$CurrentProvider\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "finops_egress_network_cost_per_month_estimate{business_model=\"$CurrentBusinessModel\",provider=\"$CurrentProvider\"} + finops_ingress_network_cost_per_month_estimate{business_model=\"$CurrentBusinessModel\",provider=\"$CurrentProvider\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "_Kafka Finops Detailed Information View",
 "tags": [ "kafka-finops" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Provider",
    "label": "Provider",
    "query": {
     "query": "label_values(finops_current_provider, provider)"
    }
   },
   {
    "name": "BusinessModel",
    "label": "Business Model",
    "query": {
     "query": "label_values(finops_current_provider, business_model)"
    }
   },
   {
    "name": "AvailabilityZones",
    "label": "Availability Zones",
    "query": {
     "query": "label_values(finops_current_provider, availability_zones)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align: center; font-size: 84px\">Detailed Information View</p>"
   }
  },
  {
   "title": "Total Monthly Topic Costs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "suffix:USD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(finops_cost_per_topic_total{business_model=\"$BusinessModel\", provider=\"$Provider\",availability_zones=\"$AvailabilityZones\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Detailed Topic Costs View",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "finops_cost_per_topic_licencing{provider=\"$Provider\", business_model=\"$BusinessModel\", availability_zones=\"$AvailabilityZones\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "finops_cost_per_topic_operational{provider=\"$Provider\", business_model=\"$BusinessModel\", availability_zones=\"$AvailabilityZones\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "finops_cost_per_partition{provider=\"$Provider\", business_model=\"$BusinessModel\", availability_zones=\"$AvailabilityZones\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "finops_cost_per_topic_per_byte{provider=\"$Provider\", business_model=\"$BusinessModel\", availability_zones=\"$AvailabilityZones\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "finops_egress_network_cost_per_month_estimate{provider=\"$Provider\", business_model=\"$BusinessModel\", availability_zones=\"$AvailabilityZones\"} + finops_ingress_network_cost_per_month_estimate{provider=\"$Provider\", business_model=\"$BusinessModel\", availability_zones=\"$AvailabilityZones\"}",
     "legendFormat": "Network"
    },
    {
     "expr": "finops_cost_per_topic_total{provider=\"$Provider\", business_model=\"$BusinessModel\", availability_zones=\"$AvailabilityZones\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network / Operational View",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (topic)(kafka_server_brokertopicmetrics_bytesout_total{topic!=\"\"})/1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (topic)(kafka_server_brokertopicmetrics_bytesin_total{topic!=\"\"})/1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (topic)(kafka_log_log_size{topic!=\"\"})/1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (topic)(kafka_server_brokertopicmetrics_messagesin_total{topic!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}